#!/bin/sh

cd /tmp
tar xf /host/distro.tar

wget -q -P bin https://github.com/zoobab/screen-static-coreos/raw/master/bin/screen
chmod +x bin/screen

apk add ncurses-terminfo
mkdir -p usr/share/terminfo/x
cp /usr/share/terminfo/x/xterm-256color usr/share/terminfo/x/

mkdir -p etc
echo "root:x:0:0:root:/root:/bin/sh" > etc/passwd

mkdir -p tmp

mkdir -p usr/local/bin
cp /host/kubeconfig usr/local/bin/
cp /host/run-k3s usr/local/bin/

tar cf /host/distro.tar *
