#!/bin/sh

ln -s busybox /bin/mount
ln -s busybox /bin/modprobe
rm -rf /bin/aux

tar cf /host/distro.tar \
    bin/find \
    $(find -L bin -samefile bin/busybox -o -samefile bin/coreutils) \
    etc/ssl/certs/ca-certificates.crt
