#!/usr/bin/env bash

# Create busybox.tar file in current directory. Contains empty tmp dir,
# plus bin/find and all links pointing to busybox or coreutils.

FINDALL="find -L bin -samefile bin/busybox -o -samefile bin/coreutils"
docker run --rm -v $PWD:/host --entrypoint /bin/sh rancher/k3s:v1.20.4-k3s1 \
       -c "ln -s busybox /bin/mount; tar cf /host/busybox.tar bin/find \$($FINDALL) tmp"
