#!/usr/bin/env bash

TARBALL=/host/busybox.tar

# WSL2 needs /bin/mount to map the windows drives into the distro.
# Add /bin/modprobe so we can drop /bin/aux.
SYMLINK="ln -s busybox /bin/mount; ln -s busybox /bin/modprobe; rm -rf /bin/aux"

# Create tarball of /bin/{busybox,coreutils,find} and all
# symlinks pointing to busybox or coreutils.
FINDALL="find -L bin -samefile bin/busybox -o -samefile bin/coreutils"

docker run --rm -v $PWD:/host --entrypoint /bin/sh rancher/k3s:v1.19.4-k3s1 \
       -c "$SYMLINK; tar cf $TARBALL bin/find \$($FINDALL) tmp"

# Fetch statically linked /bin/screen to run stuff in the background.
SCREEN="wget -q -P bin https://github.com/zoobab/screen-static-coreos/raw/master/bin/screen"

# Alpine tar doesn't support `tar rf`
docker run --rm -v $PWD:/host alpine \
       sh -c "cd /tmp; tar xf $TARBALL; $SCREEN; tar cf $TARBALL *"
