#!/usr/bin/env sh
# This is the root user's .profile script to warn people not to use the
# distribution interactively.

if busybox [[ "$-" == "*i*" ]]; then
    <<-EOF busybox tr '\n' ' ' | busybox fold -s >&2
	The ${WSL_DISTRO_NAME:-rancher-desktop} WSL distribution is not meant to be
	used to run any applications interactively. It is an implementation detail
	of Rancher Desktop. Please enable WSL integration in the Preferences to
	make the tools available in WSL distributions you install separately.
	Alternatively, the tools are available in Windows (such as via Command
	Prompt or PowerShell).
	EOF
    busybox printf "\n\n" >&2
    <<-'EOF' busybox tr '\n' ' ' | busybox fold -s >&2
	For troubleshooting Rancher Desktop, please use `rdctl shell`.
	EOF
    exit 0
fi
