# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  - push
  - pull_request
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Determine VERSION_ID
      run: |
        tag="$(git describe --tag --abbrev=0)"
        echo "VERSION_ID=${tag#v}" >> $GITHUB_ENV
    - run: make distro.tar
      env:
        BUILD_ID: ${{ github.sha }}
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: distro
        path: distro.tar
