# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  - push
  - pull_request
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Determine VERSION_ID
      run: |
        tag="$(git describe --tag --abbrev=0)"
        echo "VERSION_ID=${tag#v}" >> $GITHUB_ENV
    - run: make distro.tar
      env:
        BUILD_ID: ${{ github.sha }}
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: distro
        path: distro.tar
